// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArt6bLXlB1xJwy5uWO9O18q-Cq-NiJmtk',
    appId: '1:561965416035:web:edd38cc323221760230256',
    messagingSenderId: '561965416035',
    projectId: 'elbigayan',
    authDomain: 'elbigayan.firebaseapp.com',
    storageBucket: 'elbigayan.appspot.com',
    measurementId: 'G-EM14BCGKK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3CVTKdx-4-ISB7bLmyncpCZSZKF0NC40',
    appId: '1:561965416035:android:b5f8f7e499ca0a44230256',
    messagingSenderId: '561965416035',
    projectId: 'elbigayan',
    storageBucket: 'elbigayan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_HtCjauxCSkS1dCKvQ3Fj-wVOh53wcLc',
    appId: '1:561965416035:ios:6daafcf65eca3070230256',
    messagingSenderId: '561965416035',
    projectId: 'elbigayan',
    storageBucket: 'elbigayan.appspot.com',
    iosBundleId: 'com.example.elbigayan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_HtCjauxCSkS1dCKvQ3Fj-wVOh53wcLc',
    appId: '1:561965416035:ios:6daafcf65eca3070230256',
    messagingSenderId: '561965416035',
    projectId: 'elbigayan',
    storageBucket: 'elbigayan.appspot.com',
    iosBundleId: 'com.example.elbigayan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArt6bLXlB1xJwy5uWO9O18q-Cq-NiJmtk',
    appId: '1:561965416035:web:ea8ac366b26236e1230256',
    messagingSenderId: '561965416035',
    projectId: 'elbigayan',
    authDomain: 'elbigayan.firebaseapp.com',
    storageBucket: 'elbigayan.appspot.com',
    measurementId: 'G-MQJWZVZ9D1',
  );
}
